services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    stdin_open: true
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    volumes:
     - './frontend:/home/app'
     - notused:/home/app/node_modules
    environment:
     - NODE_ENV=development
     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
     - CHOKIDAR_USEPOLLING=true
  
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python ./main.py
    tty: true
    volumes:
      - ./backend:/app
    environment:
      PYTHONPATH: .

  pgadmin:
    image: dpage/pgadmin4
    expose:
      - 5050
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=root@example.com
      - PGADMIN_DEFAULT_PASSWORD=root
  
  db:
    image: postgres:12
    networks:
      - default
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER={{cookiecutter.db_server}}
      - POSTGRES_USER={{cookiecutter.db_user}}
      - POSTGRES_PASSWORD={{cookiecutter.db_password}}
      - POSTGRES_DB={{cookiecutter.db_name}}

volumes:
  app-db-data:
  notused: